name: Build and execute Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Install dependencies
        shell: bash
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status.
          pip install --upgrade pip  # Upgrade pip
          pip install selenium  # Install Selenium
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Execute pytest
        run: pytest tests/