name: Build and execute Python Script

on:
  push:
    branches:
      - main  # Exécute le workflow sur des changements dans la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      # Étape 1: Checkout du code source du repository
      - uses: actions/checkout@v4
        name: Checkout code

      # Étape 2: Installer Python 3.10.12
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12  # Utilise la version de Python 3.10.12

      # Étape 3: Installer les dépendances nécessaires depuis requirements.txt
      - name: Install dependencies
        shell: bash
        run: |
          pip install --upgrade pip  # Met à jour pip
          pip install selenium  # Installe Selenium
          pip install webdriver_manager
          pip install -r requirements.txt  # Installe les autres dépendances spécifiées

      # Étape 4: Exécuter les tests avec pytest (vérifie que le dossier 'tests' contient bien les tests)
      - name: Execute pytest
        run: pytest tests/  # Vérifie que ce chemin pointe vers le dossier contenant tes tests
